### ISSUE TITLE
Energy Bar a la Hunger, Breath, etc.

### ISSUE THREAD

**Issue by ruvaldak** [PaperScorpio/sprint-o-meter#1]
Would be neat to have the option to change the sprint meter to an energy bar, something along the lines of the breath bar maybe. There's an old stamina type mod that did just this: https://www.curseforge.com/minecraft/mc-mods/staminaplus

Could make the icon, like, a little yellow lightning bolt maybe, or whatever.

**Comment by Kaitaki** [comment]
This is a really interesting idea, thanks I'll look into it!

**Comment by ruvaldak** [comment]
extra points if you can relocate it/shift it downwards or upwards if, for example, a player has something that adds a bar, or removes a bar like hunger or whatever.

**Comment by Kaitaki** [comment]
Forgot to close for the last release, a bar was added under the exp bar in 2.0a!
