### ISSUE TITLE
no potion recipes

### ISSUE THREAD

**Issue by lomovoyPlayer** [PaperScorpio/sprint-o-meter#15]
I don't know if it was intended that way, but there are no replenish potion recipes

**Comment by Kaitaki** [comment]
Oops I forgot to put the recipes in the description but here are the recipes

- Instant Gain -> Swiftness Potion + Honeycomb
- Replenish -> Instant Gain + Sugar

All of the potions also have a 2 strength version (meaning you can add Glowstone to them to make them more powerful)

Hope this clears up some stuff.
