### ISSUE TITLE
Crash when joining server

### ISSUE THREAD

**Issue by Igneo220** [PaperScorpio/sprint-o-meter#21]
[crash-2023-05-22_11.23.48-client.txt](https://github.com/Kaitaki/sprint-o-meter/files/11533126/crash-2023-05-22_11.23.48-client.txt)
that would be the crash log right there, and yes there are many many other mods installed. Got a fix for me? (crashes the client, not the server)

**Comment by Igneo220** [comment]
oh, and its on 1.19.2, i saw the similar issue, butttt it does not appear to be fixed, assuming its the same problem

**Comment by Kaitaki** [comment]
Should be fixed with the next release!

**Comment by PalePyth** [comment]
same issue
