### ISSUE TITLE
Crashing when trying to join server

### ISSUE THREAD

**Issue by TheButterbrotMan** [PaperScorpio/sprint-o-meter#4]
https://bytebin.lucko.me/ZO76m0jtXX

**Comment by Kaitaki** [comment]
What version is it crashing on? 1.17? 1.18.2? 1.18.1?

**Comment by TheButterbrotMan** [comment]
1.18.2

**Comment by Kaitaki** [comment]
It looks like I can't recreate the issue, could you send a list of your mods that you are using with Sprint O' Meter? I saw that you have mods in your log so it might be a conflict with one of your mods.

**Comment by Kaitaki** [comment]
Should be fixed once 2.0 is released!
