### ISSUE TITLE
Just some bugs

### ISSUE THREAD

**Issue by cowsha** [PaperScorpio/sprint-o-meter#5]
1.Stamina drains for time you hold jump button instead of actual jumps(aka you set 5 as jump staminadrain value and while holding jump button it eats around 10-15 just for one jump) 
2.Current jump meter overlaps offhand slot:
![2022-04-04_19 11 26](https://user-images.githubusercontent.com/35926994/161546880-07ae4a4d-a734-4bf2-a632-eacfc62d69fa.png)

**Comment by Kaitaki** [comment]
Thank you! I'll work on it.

**Comment by Kaitaki** [comment]
Fixed with the release of 2.0a!
