### ISSUE TITLE
stamina is not restored

### ISSUE THREAD

**Issue by lomovoyPlayer** [PaperScorpio/sprint-o-meter#7]
stamina does not recover when in a boat (possibly in other transport, but I have not checked)
I also want to point out, in addition to other people, the movement in the boat, in theory, should spend endurance, because you need to row with oars.

**Comment by Kaitaki** [comment]
This was intentional due to some funkiness with detecting whether the player was in a vehicle or not. I will probably fix this in the next major update.

**Comment by Kaitaki** [comment]
Will be fixed once 2.0 is released.
