### ISSUE TITLE
Config to make jump not stop stamina regenerating && config to not disable jump while run of stamina

### ISSUE THREAD

**Issue by ImExoOdeex** [PaperScorpio/sprint-o-meter#9]

**Comment by ImExoOdeex** [comment]
It would be great to be able to jump while no stamina and when I have in config that jump takes 0 points, it actually stops regenerating stamina, so it would be great to see in config as well! I really love this mod

**Comment by Kaitaki** [comment]
Done! Should be fixed when 2.0 is released!
